# Generated by Django 3.2.3 on 2021-05-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_title',
            new_name='movie',
        ),
    ]
